# Generated by Django 5.1.4 on 2026-03-25 00:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Slug da fonte (ex: ibge-cities)",
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("api", "API REST"),
                            ("csv_upload", "Upload CSV"),
                            ("json_upload", "Upload JSON"),
                            ("url", "URL direta"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="URL, headers, params, file_path, etc."
                    ),
                ),
                ("schedule_cron", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DbtRun",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("command", models.CharField(default="dbt run", max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("running", "Executando"),
                            ("success", "Sucesso"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("models_run", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("output_log", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuerySession",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_question",
                    models.TextField(help_text="Pergunta em linguagem natural."),
                ),
                (
                    "generated_sql",
                    models.TextField(blank=True, help_text="SQL gerado pelo agente."),
                ),
                (
                    "result_preview",
                    models.JSONField(
                        default=list, help_text="Primeiras N linhas do resultado."
                    ),
                ),
                (
                    "result_columns",
                    models.JSONField(
                        default=list, help_text="Nomes das colunas do resultado."
                    ),
                ),
                ("row_count", models.IntegerField(default=0)),
                ("execution_time_ms", models.IntegerField(default=0)),
                ("tokens_used", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "chart_type",
                    models.CharField(
                        blank=True,
                        help_text="Tipo de gráfico sugerido pelo agente (bar, line, pie)",
                        max_length=20,
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider usado (anthropic, ollama, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Modelo usado pelo provider.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CatalogEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("table_name", models.CharField(max_length=200, unique=True)),
                (
                    "layer",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                        ],
                        max_length=10,
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "file_path",
                    models.CharField(
                        help_text="Caminho do Parquet/view", max_length=500
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        default=list,
                        help_text="Schema: [{name, dtype, nullable, description}]",
                    ),
                ),
                ("row_count", models.BigIntegerField(default=0)),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                (
                    "profile",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Profiling: null_pct, unique, min, max por coluna",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catalog_entries",
                        to="lakehouse.datasource",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Catalog entries",
                "ordering": ["layer", "table_name"],
            },
        ),
        migrations.CreateModel(
            name="IngestionLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("running", "Executando"),
                            ("success", "Sucesso"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "layer",
                    models.CharField(
                        default="bronze",
                        help_text="Camada destino (bronze)",
                        max_length=10,
                    ),
                ),
                ("rows_loaded", models.IntegerField(default=0)),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        help_text="Caminho do Parquet gerado",
                        max_length=500,
                    ),
                ),
                ("file_size_bytes", models.BigIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_logs",
                        to="lakehouse.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
